version: 1.0.{build}
image: Visual Studio 2019
configuration: Release
install:
- ps: >-
    cd src

    nuget restore UnityNuGet.sln

    $env:DEPLOY_SERVER_TO_AZURE = 'false'

    if(-Not $env:APPVEYOR_PULL_REQUEST_NUMBER) {
      if($env:appveyor_repo_tag -eq 'True') {
        if($env:appveyor_repo_tag_name -match '^[0-9]') {
           $env:DEPLOY_SERVER_TO_AZURE = 'true'
        }
      }
    }
build:
  project: src/UnityNuGet.sln
  verbosity: minimal
after_build:
- dotnet publish -o ..\build -c Release UnityNuGet.Server\UnityNuGet.Server.csproj
artifacts:
- path: src/build
  name: UnityNuGetDeploy
  type: WebDeployPackage
deploy:
  - provider: WebDeploy
    server: https://unitynuget-registry.scm.azurewebsites.net:443/msdeploy.axd?site=unitynuget-registry
    website: unitynuget-registry
    username: $unitynuget-registry
    password:
      secure: j5rB9C0QezfJlpCglmalS14+5PkTuAJ1PT9fuRFNss+5UQNAPmHcW8z4pvX1CRD6htRaorT6fe+KoySIiOwYOg==
    remove_files: false
    app_offline: true
    artifact: UnityNuGetDeploy
    on:
      branch: master
      DEPLOY_SERVER_TO_AZURE: true
